DROP DATABASE IF EXISTS AVIACAO;
CREATE DATABASE AVIACAO;
USE AVIACAO;

-- CLIENTE
CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME TEXT NOT NULL,
    CONTATO TEXT NOT NULL,
    GENERO TEXT NOT NULL,
    DATA_NASCIMENTO DATETIME NOT NULL
);


-- AEROPORTO
CREATE TABLE AEROPORTO(
	ID_AEROPORTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOCALIZACAO TEXT NOT NULL
);


-- AERONAVE
CREATE TABLE TIPO_AERONAVE(
	ID_TIPO_AERONAVE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO TEXT NOT NULL
);
CREATE TABLE AERONAVE(
	ID_AERONAVE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QTD_POLTRONAS INT NOT NULL,
    ID_TIPO_AERONAVE INT NOT NULL,
    CONSTRAINT FK_ID_TIPO_AERONAVE FOREIGN KEY(ID_TIPO_AERONAVE) REFERENCES TIPO_AERONAVE(ID_TIPO_AERONAVE)
);

-- VOO
CREATE TABLE VOO(
	ID_VOO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HORARIO_SAIDA DATETIME NOT NULL,
    HORARIO_DESTINO DATETIME NOT NULL,
    ID_AEROPORTO_SAIDA INT NOT NULL,
    ID_AEROPORTO_DESTINO INT NOT NULL,
    ID_AERONAVE INT NOT NULL,
    CONSTRAINT FK_ID_AEROPORTO_SAIDA_VOO FOREIGN KEY(ID_AEROPORTO_SAIDA) REFERENCES AEROPORTO(ID_AEROPORTO),
    CONSTRAINT FK_ID_AEROPORTO_DESTINO FOREIGN KEY(ID_AEROPORTO_DESTINO) REFERENCES AEROPORTO(ID_AEROPORTO),
    CONSTRAINT FK_ID_AERONAVE_VOO FOREIGN KEY(ID_AERONAVE) REFERENCES AERONAVE(ID_AERONAVE)
);

-- ESCALA
CREATE TABLE ESCALA(
	ID_ESCALA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HORARIO_SAIDA DATETIME NOT NULL,
    ID_VOO INT NOT NULL,
    ID_AEROPORTO_SAIDA INT NOT NULL,
    CONSTRAINT FK_ID_VOO_ESCALA FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO),
    CONSTRAINT FK_ID_AEROPORTO_SAIDA_ESCALA FOREIGN KEY(ID_AEROPORTO_SAIDA) REFERENCES AEROPORTO(ID_AEROPORTO)
);


-- HORARIO E COMPRA
CREATE TABLE HORARIO(
	ID_HORARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DISPONIBILIDADE BOOL DEFAULT TRUE,
    LADO_POLTRONA TEXT NOT NULL,
    LOCALIZACAO_POLTRONA TEXT NOT NULL,
    ID_VOO INT NOT NULL,
    CONSTRAINT FK_ID_VOO_HORARIO FOREIGN KEY(ID_VOO) REFERENCES VOO(ID_VOO)
);

CREATE TABLE COMPRA(
	ID_COMPRA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HORARIO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_ID_HORARIO FOREIGN KEY(ID_CLIENTE) REFERENCES HORARIO(ID_HORARIO),
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);