USE TRANSPORTE_AEREO;
DROP TRIGGER IF EXISTS INSERT_HORARIOS;

DELIMITER $$;
CREATE TRIGGER INSERT_HORARIOS
AFTER INSERT ON VOO
FOR EACH ROW
BEGIN 

	DECLARE CONTADOR INT;
    DECLARE QTD INT;
	SET CONTADOR = 0;
    SET QTD = (SELECT QTD_POLTRONAS FROM AERONAVE WHERE NEW.ID_AERONAVE = aeronave.ID_AERONAVE);
    WHILE(CONTADOR < QTD)
	DO
		INSERT INTO HORARIO(ID_VOO) VALUES (NEW.ID_VOO);
        SET CONTADOR = CONTADOR+1;
	END WHILE;
      
END;