USE TRANSPORTE_AEREO;
DROP PROCEDURE IF EXISTS INSERT_POLTRONAS;

DELIMITER $$;
CREATE PROCEDURE INSERT_POLTRONAS(QTD_POLTRONAS INT, AERONAVE INT)
BEGIN 

	DECLARE CONTADOR INT;
	SET CONTADOR = 0;
    WHILE(CONTADOR < QTD_POLTRONAS)
	DO
		IF(CONTADOR < (QTD_POLTRONAS*0.25)) THEN
			INSERT INTO POLTRONA (LADO, LOCALIZACAO, DISPONIBILIDADE, ID_AERONAVE)
            VALUES('Direita', 'Janela', TRUE, AERONAVE);
		ELSEIF(CONTADOR > (QTD_POLTRONAS*0.25)) AND CONTADOR < (QTD_POLTRONAS*0.50) THEN
			INSERT INTO POLTRONA (LADO, LOCALIZACAO, DISPONIBILIDADE, ID_AERONAVE)
            VALUES('Direita', 'Corredor', TRUE, AERONAVE);
		ELSEIF(CONTADOR > (QTD_POLTRONAS*0.50)) AND CONTADOR < (QTD_POLTRONAS*0.75) THEN
			INSERT INTO POLTRONA (LADO, LOCALIZACAO, DISPONIBILIDADE, ID_AERONAVE)
            VALUES('Esquerda', 'Corredor', TRUE, AERONAVE);
		ELSEIF(CONTADOR < QTD_POLTRONAS)THEN
			INSERT INTO POLTRONA (LADO, LOCALIZACAO, DISPONIBILIDADE, ID_AERONAVE)
            VALUES('Esquerda', 'Janela', TRUE, AERONAVE);
        END IF;
        
        SET CONTADOR = CONTADOR + 1; 
	END WHILE;
      
END;