USE `BD2401`;
-- Excluindo o BD
drop schema `BD2401`;

-- Criando o Schema do BD
create schema `BD2401`;

-- Criando a tabela
create table `BD2401`.`NEW_TABLE`(
	`ID_MEMBER` INT NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(20) NOT NULL,
    `ACTIVE` BIT(1) NULL DEFAULT 1,
    `WHEN_ADDED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`ID_MEMBER`)
    
);


-- INSERINDO DADOS NA TABELA

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`)
VALUES('João V Danielewicz');

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES('Bianca', 0);

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES('Emily', 0);

-- EXIBINDO/CONSULTANDO DADOS

select * from `BD2401`.`NEW_TABLE`;
delete from `BD2401`.`NEW_TABLE` where ID_MEMBER = 4;