CREATE DATABASE NORMALIZACAO;
USE NORMALIZACAO; 

/*
1FN 


CREATE TABLE NOTA_FISCAL(
	NRO_NOTA INT AUTO_INCREMENT NOT NULL,
    NOME_CLIENTE VARCHAR(50) NOT NULL,
    END_CLIENTE VARCHAR(255) NOT NULL,
    NOME_VENDEDOR VARCHAR(50) NOT NULL,
    DATA_EMISSAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALOR_TOTAL FLOAT NOT NULL,
    CONSTRAINT PK_NRO_NOTA PRIMARY KEY (NRO_NOTA)
);

CREATE TABLE ITEM_NOTA_FISCAL(
	NRO_NOTA INT NOT NULL,
    COD_PRODUTO INT NOT NULL,
    DESC_PRODUTO VARCHAR(255) NOT NULL,
    QTD_PRODUTO INT NOT NULL,
    VALOR_PRODUTO FLOAT NOT NULL,
    VALOR_TOTAL FLOAT NOT NULL,
    CONSTRAINT PK_ITEM_NOTA_FISCAL PRIMARY KEY(NRO_NOTA, COD_PRODUTO)
);
*/

CREATE TABLE NOTA_FISCAL(
	NRO_NOTA INT AUTO_INCREMENT NOT NULL,
    NOME_CLIENTE VARCHAR(50) NOT NULL,
    END_CLIENTE VARCHAR(255) NOT NULL,
    NOME_VENDEDOR VARCHAR(50) NOT NULL,
    DATA_EMISSAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALOR_TOTAL FLOAT NOT NULL,
    CONSTRAINT PK_NRO_NOTA PRIMARY KEY (NRO_NOTA)
);

CREATE TABLE ITEM_NOTA_FISCAL(
	NRO_NOTA INT NOT NULL,
    COD_PRODUTO INT NOT NULL,
    DESC_PRODUTO VARCHAR(255) NOT NULL,
    QTD_PRODUTO INT NOT NULL,
    VALOR_PRODUTO FLOAT NOT NULL,
    VALOR_TOTAL FLOAT NOT NULL,
    CONSTRAINT PK_ITEM_NOTA_FISCAL PRIMARY KEY(NRO_NOTA, COD_PRODUTO)
);

CREATE TABLE PRODUTO(
	COD_PRODUTO INT AUTO_INCREMENT NOT NULL,
    DESC_PRODUTO VARCHAR(255) NOT NULL,
    UN_MED VARCHAR(15) NOT NULL,
    VL_PRODUTO FLOAT NOT NULL
);
