USE AVIACAO;

-- Listagem de Aeronaves ordenadas por tipo
SELECT 
TP.DESCRICAO, AN.* 
FROM 
TIPO_AERONAVE AS TP, AERONAVE AS AN
WHERE
 AN.ID_TIPO_AERONAVE = TP.ID_TIPO_AERONAVE
ORDER BY
DESCRICAO;

-- Relatório de Vôos das Aeronaves por período (dia/semana/mês)
-- Voos de antes de Maio/2024.
SELECT 
V.ID_VOO,
A1.LOCALIZACAO AS AEROPORTO_SAIDA, V.HORARIO_SAIDA,
A2.LOCALIZACAO AS AEROPORTO_DESTINO, V.HORARIO_DESTINO
FROM
VOO AS V, AEROPORTO AS A1, AEROPORTO AS A2
WHERE
HORARIO_SAIDA < 20240501 
AND
V.ID_AEROPORTO_SAIDA = A1.ID_AEROPORTO 
AND
V.ID_AEROPORTO_DESTINO = A2.ID_AEROPORTO;


-- c) Listagem de vôos que fazem escala
-- em um determinado local;
-- Vôos que fazem escala em Amsterdã
SELECT
V.ID_VOO,
A1.LOCALIZACAO AS SAIDA,
A2.LOCALIZACAO AS ESCALA,
A3.LOCALIZACAO AS DESTINO
FROM
VOO AS V, AEROPORTO AS A1, AEROPORTO AS A2,
AEROPORTO AS A3, ESCALA AS E
WHERE
E.ID_AEROPORTO_SAIDA  = 5 AND
V.ID_VOO = E.ID_VOO AND
V.ID_AEROPORTO_SAIDA = A1.ID_AEROPORTO AND
E.ID_AEROPORTO_SAIDA = A2.ID_AEROPORTO AND
V.ID_AEROPORTO_DESTINO = A3.ID_AEROPORTO;

-- d) Exibição de poltronas disponíveis em um determinado vôo/avião;
-- Ordenação de voos dos mais vazios para os mais ocupados
SELECT 
H.ID_VOO,
COUNT(H.ID_HORARIO) AS QUANTIDADE_DISPONIVEL,
A.LOCALIZACAO AS DESTINO
FROM 
HORARIO AS H, VOO AS V, AEROPORTO AS A
WHERE
DISPONIBILIDADE = TRUE AND
H.ID_VOO = V.ID_VOO AND
V.ID_AEROPORTO_DESTINO = A.ID_AEROPORTO
GROUP BY ID_VOO
ORDER BY QUANTIDADE_DISPONIVEL DESC;



SELECT
V.ID_VOO,
COUNT(H.ID_HORARIO) AS QTD_HORARIOS,
A.ID_AERONAVE,
A.QTD_POLTRONAS
FROM
VOO AS V, HORARIO AS H, AERONAVE AS A
WHERE
H.ID_VOO = V.ID_VOO AND
V.ID_AERONAVE = A.ID_AERONAVE
GROUP BY V.ID_VOO