USE AVIACAO;
DROP TRIGGER IF EXISTS UPDATE_HORARIO;

DELIMITER $$
CREATE TRIGGER UPDATE_HORARIO
BEFORE INSERT ON COMPRA
FOR EACH ROW
BEGIN 
	UPDATE HORARIO SET DISPONIBILIDADE = FALSE WHERE NEW.ID_HORARIO = HORARIO.ID_HORARIO;
END$$


